import { NextRequest, NextResponse } from "next/server";
import ExcelJS from "exceljs";
import type { ExtractionResult } from "@/lib/types";

export async function POST(req: NextRequest) {
  try {
    const data: ExtractionResult = await req.json();
    const workbook = new ExcelJS.Workbook();

    // ─── Sheet 1: Instructions ───
    const instrSheet = workbook.addWorksheet("Instructions");
    instrSheet.getCell("B1").value =
      "This workbook enables you to bulk add and update benefits on an initiative or project.";
    instrSheet.getCell("B2").value =
      "It is imperative that the workbook structure is not changed for it to be accepted by the uploader. The 'data (including headers)' must always begin in cell B6.";
    instrSheet.getCell("B3").value =
      "Do not add more header rows or left columns, as this will result in the uploader not recognizing the sheet contents and your upload failing.";
    instrSheet.getCell("B4").value =
      "You can use formulas and validation in this workbook, but note that formulas cannot be generated by the template download. When you download the template, you will only see values and will need to re-add any formulas or validation.";

    // ─── Sheet 2: Initiatives ───
    const initSheet = workbook.addWorksheet("Initiatives");
    addInstructions(initSheet);
    initSheet.getRow(6).values = [
      null,
      "Initiative ID",
      "Initiative",
      "Initiative Status",
      "Methodology",
      "Owner Email",
    ];
    styleHeaderRow(initSheet, 6);

    data.initiatives.forEach((init, i) => {
      initSheet.getRow(7 + i).values = [
        null,
        init.cpInitiativeId || `MISSING-ID-${i + 1}`,
        init.name,
        init.status,
        init.methodology,
        init.ownerEmail,
      ];
    });

    // ─── Sheet 3: Benefits Field Options ───
    const bfoSheet = workbook.addWorksheet("Benefits Field Options");
    addInstructions(bfoSheet);
    bfoSheet.getRow(6).values = [
      null,
      "Benefit Name",
      "Question",
      "Applies To",
      "Question Type",
      "Allow Multi Select",
      "DDOption1",
      "DDOption2",
      "DDOption3",
      "DDOption4",
      "DDOption5",
      "DDOption6",
      "DDOption7",
      "DDOption8",
    ];
    styleHeaderRow(bfoSheet, 6);

    // Fixed rows (same for every project)
    const bfoRows = [
      [
        "All",
        "Profile Status",
        "Profiles",
        "DropDown",
        "False",
        "At risk",
        "Awaiting sign-off",
        "Cancelled",
        "In-flight",
        "On Hold",
        "Signed-off",
        "Target",
      ],
      [
        "Savings",
        "Workstream",
        "Both, for comparisons",
        "Free Text",
        "False",
      ],
      [
        "Savings",
        "Business Unit",
        "Both, for comparisons",
        "Free Text",
        "False",
      ],
      [
        "Savings",
        "Expenditure",
        "Both, for comparisons",
        "Dropdown",
        "False",
        "Opex",
        "Capex",
      ],
      ["Savings", "Sign-Off Date", "Profiles", "Date", "False"],
      [
        "Savings",
        "Type",
        "Profiles",
        "Dropdown",
        "False",
        "One off",
        "Recurring",
      ],
      [
        "Savings",
        "Savings Methodology",
        "Profiles",
        "Dropdown",
        "False",
        "Unit Price reduction",
        "Demand management",
        "Cost mitigation",
        "Payment terms",
        "Value creation",
        "Cost avoidance",
        "Volume rebate",
        "Total cost of ownership",
      ],
    ];
    bfoRows.forEach((row, i) => {
      bfoSheet.getRow(7 + i).values = [null, ...row];
    });

    // ─── Sheet 4: Dates, Targets & Estimates ───
    const dteSheet = workbook.addWorksheet("Dates, Targets & Estimates");
    addInstructions(dteSheet);
    dteSheet.getRow(6).values = [
      null,
      "Benefit Name",
      "Financial year start month",
      "Benefit Reporting Period",
      "Unit Of Measurement",
      "Initiative ID",
      "Initiative",
      "In-year start date",
      "In-year end date",
      "Total Baseline Estimate",
      "Addressable Baseline Estimate",
      "Low Target",
      "Mid Target",
      "High Target",
    ];
    styleHeaderRow(dteSheet, 6);

    data.initiatives.forEach((init, i) => {
      const t = init.targets;
      dteSheet.getRow(7 + i).values = [
        null,
        t?.benefitName || "Savings",
        t?.fyStartMonth || "N/A",
        t?.reportingPeriod || "Monthly",
        t?.unitOfMeasurement || "USD",
        init.cpInitiativeId || `MISSING-ID-${i + 1}`,
        init.name,
        t?.inYearStartDate || "",
        t?.inYearEndDate || "",
        t?.totalBaselineEstimate || 0,
        t?.addressableBaselineEstimate || 0,
        t?.lowTarget || 0,
        t?.midTarget || 0,
        t?.highTarget || 0,
      ];
    });

    // ─── Sheet 5: Savings | Baselines ───
    const basSheet = workbook.addWorksheet("Savings | Baselines");
    addInstructions(basSheet);
    basSheet.getRow(6).values = [
      null,
      "Initiative ID",
      "Initiative",
      "Baseline Name",
      "Expenditure",
      "Workstream",
      "Business Unit",
      "Annualised Baseline",
      "Baseline FY 2024-2025",
      "Baseline FY 2025-2026",
    ];
    styleHeaderRow(basSheet, 6);

    data.initiatives.forEach((init, i) => {
      const b = init.baseline;
      if (b) {
        basSheet.getRow(7 + i).values = [
          null,
          init.cpInitiativeId || `MISSING-ID-${i + 1}`,
          init.name,
          b.baselineName,
          b.expenditure,
          b.workstream,
          b.businessUnit,
          b.annualisedBaseline,
          b.baselineFY1,
          b.baselineFY2,
        ];
      }
    });

    // ─── Sheet 6: Savings | Profiles ───
    const profSheet = workbook.addWorksheet("Savings | Profiles");
    addInstructions(profSheet);

    // Build month headers (current year, Jan-Dec)
    const currentYear = new Date().getFullYear();
    const monthHeaders: string[] = [];
    for (let m = 0; m < 12; m++) {
      const date = new Date(currentYear, m, 1);
      monthHeaders.push(
        date.toLocaleDateString("en-US", { month: "2-digit", day: "2-digit", year: "numeric" })
      );
    }

    profSheet.getRow(6).values = [
      null,
      "Initiative ID",
      "Initiative",
      "Profile Name",
      "Status",
      "Link With Baseline",
      "Annualised Baseline",
      "Expenditure",
      "Type",
      "Savings Methodology",
      "Workstream",
      "Business Unit",
      "Sign-Off Date",
      "Annualised Savings",
      ...monthHeaders,
    ];
    styleHeaderRow(profSheet, 6);

    let profRow = 7;
    data.initiatives.forEach((init) => {
      init.profiles.forEach((p) => {
        const monthly =
          p.monthlySavings.length === 12
            ? p.monthlySavings
            : Array(12).fill(0);
        profSheet.getRow(profRow).values = [
          null,
          init.cpInitiativeId || `MISSING-ID`,
          init.name,
          p.profileName,
          p.status,
          p.linkWithBaseline,
          p.annualisedBaseline,
          p.expenditure,
          p.type,
          p.savingsMethodology,
          p.workstream,
          p.businessUnit,
          p.signOffDate,
          p.annualisedSavings,
          ...monthly,
        ];
        profRow++;
      });
    });

    // Auto-width columns on all sheets
    workbook.eachSheet((sheet) => {
      sheet.columns?.forEach((col) => {
        let maxLen = 10;
        col.eachCell?.({ includeEmpty: false }, (cell) => {
          const len = cell.value ? String(cell.value).length : 0;
          if (len > maxLen) maxLen = Math.min(len, 40);
        });
        col.width = maxLen + 2;
      });
    });

    // Write to buffer
    const buffer = await workbook.xlsx.writeBuffer();

    return new NextResponse(buffer as ArrayBuffer, {
      headers: {
        "Content-Type":
          "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "Content-Disposition": `attachment; filename="${data.projectName}_CP_Upload.xlsx"`,
      },
    });
  } catch (error) {
    console.error("Generate error:", error);
    return NextResponse.json(
      { error: "Failed to generate file" },
      { status: 500 }
    );
  }
}

function addInstructions(sheet: ExcelJS.Worksheet) {
  sheet.getCell("B1").value =
    "This workbook enables you to bulk add and update benefits on an initiative or project.";
  sheet.getCell("B2").value =
    "It is imperative that the workbook structure is not changed for it to be accepted by the uploader. The 'data (including headers)' must always begin in cell B6.";
  sheet.getCell("B3").value =
    "Do not add more header rows or left columns, as this will result in the uploader not recognizing the sheet contents and your upload failing.";
  sheet.getCell("B4").value =
    "You can use formulas and validation in this workbook, but note that formulas cannot be generated by the template download. When you download the template, you will only see values and will need to re-add any formulas or validation.";
}

function styleHeaderRow(sheet: ExcelJS.Worksheet, rowNum: number) {
  const row = sheet.getRow(rowNum);
  row.font = { bold: true };
  row.eachCell((cell) => {
    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FFE8EDF5" },
    };
    cell.border = {
      bottom: { style: "thin", color: { argb: "FFB0B0B0" } },
    };
  });
}
